---
# app2 added to app, forgotten in prod.
all:
  children:
    app:
      hosts:
        app1:
        app2:
        stg-app1:
    db:
      hosts:
        db1:
        stg-db1:
    prod:
      hosts:
        app1:
        db1:
    staging:
      hosts:
        stg-app1:
        stg-db1:
