# Variables on the host line: each value goes through Python's literal_eval
[postgresql]
db1 postgresql_port=5432 postgresql_ssl=true postgresql_fsync=True postgresql_version="16" postgresql_socket_mode=0770 postgresql_archive=no postgresql_listen="['10.10.0.1', '127.0.0.1']" postgresql_conf="{'max_connections': 200}"
