---
# app1 copied into staging and left in prod.
all:
  children:
    app:
      hosts:
        app1:
        stg-app1:
    db:
      hosts:
        db1:
        stg-db1:
    prod:
      hosts:
        app1:
        db1:
    staging:
      hosts:
        app1:
        stg-app1:
        stg-db1:
