---
# db2 added under all, in no group.
all:
  hosts:
    db2:
  children:
    app:
      hosts:
        app1:
        stg-app1:
    db:
      hosts:
        db1:
        stg-db1:
    prod:
      hosts:
        app1:
        db1:
    staging:
      hosts:
        stg-app1:
        stg-db1:
