---
# First attempt at a fix: give backup a higher priority. It is still at
# depth 1, and db at depth 2.
all:
  children:
    postgresql:
      children:
        db:
          hosts:
            db1:
            db2:
    backup:
      vars:
        ansible_group_priority: 10
      hosts:
        db1:
